### ISSUE TITLE
Can I remove the `state_is_tuple=True` parameter?

### ISSUE THREAD

**Issue by hanfeisun** [pender/chatbot-rnn#10]
https://github.com/pender/chatbot-rnn/blob/master/model.py#L27

The `state_is_tuple` parameter in model.py will cause error (for tensorflow 0.12.1)
`TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'
`

WIll it be ok if I delete this parameter?

**Comment by charlestruluck** [comment]
Looks like a pull request must have got accepted that shouldn't have. Removing the changes #4 made seems to have fixed it for me.

**Comment by Mayanksoni20** [comment]
Yes. You can remove it. By default in tensorflow >10 , the statement is true.

I was facing the same issue , removed it and it works fine.

**Comment by pender** [comment]
Hi, I pushed a significant update to TF 1.4 and Python3, so I am closing out old issues -- feel free to reopen if this is still a problem, and I will take a look.
