### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by crawfordk37** [pender/chatbot-rnn#2]
I have been trying to get tensorflow to work for a while, and the only way to fix it for me seems to be to use Python 3.5 instead of 2.7. Using 2.7 seems to cause this issue and I have no idea how to fix it. Suggestions?

**Comment by pender** [comment]
No, sorry. If you're having trouble installing tensorflow, you could try some of the tensorflow resources (like the [tensorflow github page](github.com/tensorflow/tensorflow)).

**Comment by jrao1** [comment]
@crawfordk37 It's fairly easy to get this to work under 3.5, for the TypeError, just add 'rb' to all open function:

`with open(config_path, 'rb') as f:`

`with open(vocab_path, 'rb') as f:`

You'll also need to:
* change cPickle import to `import _pickle as cPickle`
* change `raw_input` to `input`
* change `xrange` to `range`
* Make sure all print is called as function: there're two lines in utils.py where print has no parenthesis

**Comment by saurabhzuve** [comment]
I'm getting this error when I run the train.py
  File "C:/Users/xxxxxxxx/Documents/ChatBotTicket/chatbot-rnn-master/model.py", line 3, in <module>
    from tensorflow.python.ops import seq2seq

ImportError: cannot import name 'seq2seq'
