### ISSUE TITLE
Reddit-parser

### ISSUE THREAD

**Issue by nichcuta** [pender/chatbot-rnn#21]
Reddit-parser doesn't work with reddit data gathered between RC_2005-12 and RC_2007-10, while also from RC_2015-08 till RC_2017-06. I am trying to edit the reddit_parse.py myself although it will take me some time to figure it out.

PS: The main reason it fails is due to jason tags 'ups', 'downs', and 'name' are missing in the above mentioned list of data files.

![downs error](https://user-images.githubusercontent.com/25469431/28501067-2f98c0cc-6fd4-11e7-8bdb-df42f2c11a43.png)
![name error](https://user-images.githubusercontent.com/25469431/28501068-2f9d187a-6fd4-11e7-89c0-207697637273.png)

Could someone perhaps help me figure this out please :)?

**Comment by pender** [comment]
I spent a long time with `reddit-parse.py` and it should all be fixed now (although now it runs in Python 3). Just reopen the issue if you still have problems.
