### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by Mayanksoni20** [pender/chatbot-rnn#22]

**Comment by shivajid** [comment]
Any update for this issues?

**Comment by Mayanksoni20** [comment]
Replacing all datatypes which are float32 to int32 would solve this problem.

You can do a ctrl+f to search float32 datatypes and replace that by int32

**Comment by charlesashby** [comment]
Try:

    embedding = tf.get_variable("embedding", [args.vocab_size, args.rnn_size], dtype='int32')

**Comment by pender** [comment]
Hi, I pushed a significant update to TF 1.4 and Python3, so I am closing out old issues -- feel free to reopen if this is still a problem, and I will take a look.
