### ISSUE TITLE
Can't Import name seq2seq with Tensorflow version 1.2.1

### ISSUE THREAD

**Issue by DilipRenkila** [pender/chatbot-rnn#23]
What version of tensorflow works for this project?
> dilip@dilip-ThinkPad:~/chatbot-rnn$  python chatbot.py 
> Traceback (most recent call last):
>   File "chatbot.py", line 14, in <module>
>     from model import Model
>   File "/home/dilip/chatbot-rnn/model.py", line 3, in <module>
>     from tensorflow.python.ops import seq2seq
> ImportError: cannot import name seq2seq

**Comment by NarahariKaushik** [comment]
Try
import tensorflow.contrib.seq2seq as seq2seq

**Comment by modInfo** [comment]
> import tensorflow.contrib.seq2seq as seq2seq

not working :c

**Comment by AdritaBarari** [comment]
> from tensorflow.contrib import seq2seq

worked for me.

**Comment by milkrong** [comment]
now the seq2seq is under tesorflow.contrib.legacy_seq2seq.python.ops

**Comment by boardem** [comment]
i used the following with tensorflow 1.4.0:
from tensorflow.contrib import seq2seq

**Comment by pender** [comment]
I finally pushed a significant update to TF 1.4 and Python3, so it should all run out of the box now -- just let me know if there are any further issues.
