### ISSUE TITLE
Order of function arguments slip-up

### ISSUE THREAD

**Issue by greninja** [pender/chatbot-rnn#24]
Shouldn't it be  `tf.concat(outputs, 1)` instead of the other way around because the first argument this particular function expects is `values`, [on this line](https://github.com/pender/chatbot-rnn/blob/master/model.py#L129) ?

**Comment by pender** [comment]
As I recall, TF 1.0 reordered the arguments of `tf.concat()` which caused a number of problems like this. I've now updated the code base to TF 1.4 and Python3 which should fix these problems.
