### ISSUE TITLE
problem with respone

### ISSUE THREAD

**Issue by liukimnghia** [pender/chatbot-rnn#25]
i have use the pre-train model and i test with some context : hi, hello but the respone is strange characters . 
![error](https://user-images.githubusercontent.com/18194998/30257690-fe75741e-96dd-11e7-9416-7cd772171eca.png)

**Comment by pender** [comment]
Hi, I pushed a significant update to TF 1.4 and Python3, so I am closing out old issues -- feel free to reopen if this is still a problem with the new pretrained model that I uploaded, and I will take a look.
