### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XenoGaming** [pender/chatbot-rnn#27]
I got an error while trying to run it. Here's a picture 
![image](https://user-images.githubusercontent.com/21233279/31051394-0e261e5c-a635-11e7-96c0-f5db55fc0bc3.png)

**Comment by pender** [comment]
Hi, I pushed a significant update to TF 1.4 and Python3, so I am closing out old issues -- feel free to reopen if this is still a problem, and I will take a look.
