### ISSUE TITLE
Reddit parser

### ISSUE THREAD

**Issue by bshao001** [pender/chatbot-rnn#28]
I have no experience with reddit, and don't know how torrent works. Does the Reddit parser given in this project requiring download the torrent file or the .bz2 file? I assume it requires the .bz2 file. I followed the link, but I could not find any .bz2 file. Instead, I can only download a torrent file. Could you please give me some guidance of how to get the .bz2 file on https://www.reddit.com/r/datasets/comments/3bxlg7/i_have_every_publicly_available_reddit_comment/? Thank you very much!

**Comment by pender** [comment]
Hi @bshao001, you don't need any experience with Reddit, but you do need to use a BitTorrent client to download the (very large) files. You might try [Transmission](https://transmissionbt.com/) -- install that and then open the torrent file with Transmission to download the data. Please note that a successful download will require other people in the world to be "seeding" the torrent. Wikipedia has [a good description of BitTorrent](https://en.wikipedia.org/wiki/BitTorrent) -- what it is and why it exists -- that may be helpful if you need more background on torrent files.

I should also note that my repo was developed with TensorFlow v0.12, and the API changes in TensorFlow 1.0 broke it, so it will need updating to work with a current version of TensorFlow. I will update the repo at some point but wanted to mention this so you don't spend a lot of time with BitTorrent only to later find out that it still doesn't work.

**Comment by bshao001** [comment]
Hi @pender, thank you so much for the quick response. I will try the BitTorrent client. 

Concerning the TensorFlow issue, I have already had a working version, actually two working versions, for the chatbot: one with Legacy seq2seq model in TF 1.2 and the other in the new NMT model in TF 1.3. I also have a pretty good training data set, part of that hand-drafted, part of that cleaned from the Cornell Movie Dialogs. However, with the extreme cleaning process (getting rid of too many pairs to satisfy my criteria, such as no cursing words in the answers), I am looking for more training data. And your Reddit Parser really interests me. Thank you again for the help!

**Comment by bshao001** [comment]
Hi @pender, sorry I had to reopen this issue. I tried it and finally got it kind of work. I had firstly manipulated the decoding (so that the filtering can work) and then encode (so that data can be written to the output file). However, when I extra the output file to a txt file, I see ">" in between some of the sentences. However, I assume ">" is really used to indicate a new comment. I checked some of them, and I feel that they are really a new start. Although I see that you have something called depth. As I have no experiences with Reddit, I don't know the data details.

I think what most people want are really two-sentence pairs: a question and an answer, or a statement with a response. Does the generated file meet this requirement, i.e. the all odd lines are the first statements, while the even lines are the second statements of the same pairs?

**Comment by pender** [comment]
Hi @bshao001 , no, the reddit-parse script generates text files containing multi-line conversations, where each line starts with "> " and where there is a blank line between conversations, and it eliminates conversations with fewer than four lines (but has no maximum number of lines). You'll need to revise the script substantially if you're looking for just two-line pairs.

**Comment by bshao001** [comment]
Hi @pender, thanks again for the quick response. Two questions:
1. Why there are some comments that contains ">" which looks like missing a newline separator before it?
2. When you say multi-line conversations, for one conversation, is that only between two people, such as:
A: How are you doing?
B: I am fine, thank you. And you?
A: I am fine, too. How about your kids?
B: They are good too. Thanks.
OR, a conversation among multiple people, mainly one topic starter, and followed with responses from several people. 
If it is ABAB case, then it is great. If it is ABCD case, then I would like to get rid of CD and anything after, only keeping AB.

Also, if depth the count of ABAB (or ABCD)? For example, if ABAB, then it is 4; if ABCDEF, then it is 6?

Please advise! I appreciate very much your time and help!

**Comment by bshao001** [comment]
I figured it out and updated the parser. It can now generate the data in the required format. I also have cleaning scripts available in my project. Thank you very much for the help!
