### ISSUE TITLE
ValueError:squeeze_dims[0] not in [0,0). for 'rnnlm/Squeeze' (op: 'Squeeze') with input shapes: [].

### ISSUE THREAD

**Issue by Arvind6353** [pender/chatbot-rnn#32]
Getting this below error when i ran python chatbot.py after using the pre trained model.

Any help?

**Comment by gowthambalachandhiran** [comment]
I am facing the same error.

**Comment by pender** [comment]
Hi, I pushed a significant update to TF 1.4 and Python3, so I am closing out old issues -- feel free to reopen if this is still a problem, and I will take a look.
