### ISSUE TITLE
Do you need any help with the repo?

### ISSUE THREAD

**Issue by AlexandruSimandi** [pender/chatbot-rnn#36]
Hello brother, gender not implied, I navigated across multiple ML repos and tested them on the reddit dataset and I have to say, yours is the most promising as well as well written and optimized. I am trying to build a personal assistant and I just started scratching the ML business. So yeah, I would like to support your repo in any way necessary

**Comment by pender** [comment]
Thanks, glad the repo is helpful to you. It's pretty much finished from my perspective, but if you're looking for a project to undertake, two that come to mind are (1) replacing [my "Partitioned RNN" architecture](https://github.com/pender/chatbot-rnn/blob/82cbb710beaf15da11b60e03f00bdbfd521df754/model.py#L12) with OpenAI's [block sparse kernels](https://blog.openai.com/block-sparse-gpu-kernels/) -- a much more efficient and elegant gesture toward the same goal, which may be able to improve the results substantially, and (2) playing around with the reddit-parse.py configuration to come up with better or more interesting conversations (or optimizing it for multiprocessing).
