### ISSUE TITLE
Preparing Own content for train

### ISSUE THREAD

**Issue by praveenrengarajan** [pender/chatbot-rnn#37]
I am trying to create Q&A bot type, how should be my training data format. its should be like 
`> Q: why?`
`> A: answer1`
`> Q: who?`
`> A: answer2`

or it should be only answers to the conversation?
`> answer1`
`>answer2`
@pender

**Comment by pender** [comment]
The easiest would be training data of two lines per conversation, each line starting with '>'. For example:

```
> How many legs does a cow have?
> A cow has four legs.

> What color is a lemon?
> Lemons are yellow.
```

But, my repo is probably not the best architecture for simple Q&A without context being carried over between questions. You're probably better off looking at the Tensorflow tutorials for language translation ("seq2seq" models), and then thinking of it as translating questions into answers.
