### ISSUE TITLE
'Namespace' object has no attribute 'num_blocks'

### ISSUE THREAD

**Issue by fajarnugrohoid** [pender/chatbot-rnn#39]
Hi, thank you for share your code, I have tried but I got error attributes 'num_blocks' and 'block_size', do you any suggestion : model.py", line 140, in __init__

**Comment by pender** [comment]
Happy to try to help with this -- could you copy and paste the command that you entered and the full error message that you got?

**Comment by fajarnugrohoid** [comment]
I have tried once again, but I don't know after I restarted computer, it's work.
But may be I have another problem when I train a model, I will try it first, if there's still having issue, I will ask you, thank you for your help.
