### ISSUE TITLE
Questions on Training Dataset

### ISSUE THREAD

**Issue by BFMarks** [pender/chatbot-rnn#40]
Thanks for the great repo, quick questions though:

- What is the minimum amount of data rows would you recommend for a new dataset?
- What is the exact ideal format for reformatting a new dataset?
- Can it not be that negative with a different dataset (and lighten up a little)?

**Comment by pender** [comment]
> What is the minimum amount of data rows would you recommend for a new dataset?

I'd say a few megabytes compressed is probably the minimum. Bigger models will need greater amounts of data to avoid overfitting.

> What is the exact ideal format for reformatting a new dataset?

Multiple lines of dialogue, each starting with "> " (note the space) and an empty newline between dialogues.

> Can it not be that negative with a different dataset (and lighten up a little)?

Yes, a data set with less negative content will probably result in a bot with a less negative tone.

**Comment by BFMarks** [comment]
Nice!  Thank you so much.  One last question on response time.  I'm hooking this chatbot up to another chatbot for a project.  My understanding is that there isn't a way to speed up the response time without the model producing complete gibberish.  Any ideas on speeding up the response time?

Best,
