### ISSUE TITLE
Run chatbot.py on Linux raspberrypi 4.9.80-v7+

### ISSUE THREAD

**Issue by mpakunderscore** [pender/chatbot-rnn#41]
Python 3.5.3
TensorFlow 1.4.0

Total/Free
Mem: 927/820
Swap: 2047/2024

Total Used Available Use%
/dev/root 7602088 6214644 1046052  86%

Creating model...
Restoring weights...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.OutOfRangeError: models/reddit/model.ckpt-4735000.data-00000-of-00001; Value too large for defined data type
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

So - i set swap size to 3000, but i guess this isn't work because of limit of space on SD card. And model cannot fit into memory. Is this correct?

**Comment by pender** [comment]
I think that's right -- the trained parameters alone are several gigabytes, so I doubt it will be possible to run it on a Raspberry Pi. But you could train a much smaller model to that end.
