### ISSUE TITLE
Encountering some error

### ISSUE THREAD

**Issue by vibhavk** [pender/chatbot-rnn#42]
Traceback (most recent call last):
  File "chatbot.py", line 325, in <module>
    main()
  File "chatbot.py", line 40, in main
    sample_main(args)
  File "chatbot.py", line 60, in sample_main
    model_path, config_path, vocab_path = get_paths(args.save_dir)
  File "chatbot.py", line 56, in get_paths
    raise ValueError('save_dir is not a valid path.')
ValueError: save_dir is not a valid path.

**Comment by vasiabratchuk** [comment]
Hi! I am encountering the same error. Could you please give a hint to what the fix was?

**Comment by vasiabratchuk** [comment]
Ok, got it. Just had to rename the folder to "reddit" and move all the underlying files to the top.

**Comment by belligerentbeagle** [comment]
which folder do we rename to reddit?

**Comment by claudetheboof** [comment]
im trying to implement this on Google COlab but im currently running into a few problem , mainly because im new to Colab, anyway what did you do to fix save_dir issue?

**Comment by thewaifuai** [comment]
`mv data/reddit models`. The `README` instructs us to place the pre-trained model in the data folder but we are supposed to place it in the models folder. Therefore if you followed the instructions the pre-trained model would be at `data/reddit` and the solution would be to move it to the models with the command `mv data/reddit models`.

**Comment by paulhldbrndt** [comment]
> Hi! I am encountering the same error. Could you please give a hint to what the fix was?

did you manage to fix it?

**Comment by eigenpaul** [comment]
hello @vibhavk did you manage to fix it? i have the same issue

**Comment by Natercia18** [comment]
I have the same problem. My diractory is models/reddit but it's not change.
