### ISSUE TITLE
How to get multiple response candidates?

### ISSUE THREAD

**Issue by hanfeisun** [pender/chatbot-rnn#8]
I saw there is a "beam_search" parameter in chatbot-rnn.

Would it be possible to output multiple candidates for response?

**Comment by pender** [comment]
Not planning to implement that feature. Beam search wouldn't easily facilitate it. Easiest way would be to try the same line of chat twice and see the different responses. There are more sophisticated techniques (used in the "suggested reply" feature of some commercial email and chat clients) to make the various replies as different from one another as possible... but I don't know how to do that.
